/** DEV-01/20/21/22/31/32/67 — real browser, isolated server per run. */
import {spawn} from 'node:child_process';
import {writeFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.AURUM_PLAYWRIGHT_MODULE??'playwright-core');
const port=Number(process.env.AURUM_QA_PORT??3020),origin=`http://127.0.0.1:${port}`;
const server=spawn(process.execPath,process.env.AURUM_RELEASE_SERVER?[process.env.AURUM_RELEASE_SERVER]:['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',String(port)],
  {env:{...process.env,HOSTNAME:'127.0.0.1',PORT:String(port)},stdio:['ignore','pipe','pipe']});
let log='';server.stdout.on('data',d=>log+=d);server.stderr.on('data',d=>log+=d);
let browser;const outcomes=[],errors=[];
const options={headless:true,...(process.env.AURUM_BROWSER_EXECUTABLE?{executablePath:process.env.AURUM_BROWSER_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']}: {})};
try {
  for(let i=0;i<100;i++){try{const r=await fetch(origin+'/itaipu');if(r.ok)break;}catch{}await new Promise(r=>setTimeout(r,200));if(i===99)throw Error(log);}
  browser=await chromium.launch(options);
  const context=await browser.newContext({acceptDownloads:true,viewport:{width:1280,height:1000}});
  const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));
  await page.goto(origin+'/itaipu');await page.getByRole('button',{name:'+1 tick',exact:true}).waitFor();
  await page.getByRole('button',{name:'+1 tick',exact:true}).click();
  await page.getByText('Estruturas e lotes — alternativa ao mapa',{exact:true}).click();
  await page.getByRole('button',{name:'Lote 1',exact:true}).click();
  await page.getByRole('button',{name:'Construir casa',exact:true}).click();
  await page.getByRole('button',{name:'Pausar',exact:true}).click();
  for(let i=0;i<110;i++)await page.getByRole('button',{name:'+1 tick',exact:true}).click();
  await page.getByText('Primeira casa abastecida ✓',{exact:false}).waitFor({timeout:15000});
  await page.getByText('✓ Confira energia e moradores:',{exact:false}).waitFor();
  outcomes.push({id:'DEV-01',flow:'install/build → select lot → construct → deliver → serviced home',status:'PASS'});
  const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Verificar e salvar partida',exact:true}).click();
  const download=await downloading,file=await download.path();assert(file);
  await page.locator('input[type=file]').setInputFiles(file);
  await page.getByText('Partida reexecutada e carregada com o mesmo mapa e regras.',{exact:true}).waitFor();
  outcomes.push({id:'DEV-32',flow:'export/import verified replay',status:'PASS'});
  await page.getByRole('button',{name:'Exportar save original',exact:true}).click();
  const tickBefore=await page.evaluate(()=>JSON.parse(localStorage.getItem('aurum:itaipu:autosave:v1')).frameCount);
  await page.reload();await page.getByText('Save local verificado e recuperado. Partida pausada.',{exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('aurum:itaipu:autosave:v1')).frameCount),tickBefore);
  outcomes.push({id:'DEV-31',flow:'reload recovers exact journal, remains paused',status:'PASS'});
  await page.locator('input[type=file]').setInputFiles({name:'corrupt.json',mimeType:'application/json',buffer:Buffer.from('{"semantic_id":"RM4"}')});
  await page.locator('span').filter({hasText:new RegExp('^Tick '+tickBefore+' ·')}).waitFor();
  assert.equal(await page.getByRole('button',{name:'+1 tick',exact:true}).isEnabled(),true);
  outcomes.push({id:'DEV-68',flow:'bad file preserves valid session',status:'PASS'});
  const canvas=page.locator('canvas').first();await canvas.focus();await page.keyboard.press('Space');
  await page.getByRole('button',{name:'Pausar',exact:true}).waitFor();await page.keyboard.press('Space');
  await page.getByRole('button',{name:'Rodar',exact:true}).waitFor();
  await page.getByRole('combobox',{name:'Construção',exact:true}).focus();await page.keyboard.press('Space');
  assert.equal(await page.getByRole('button',{name:'Rodar',exact:true}).isVisible(),true);
  outcomes.push({id:'DEV-19',flow:'keyboard pause, input suppression',status:'PASS'});
  await page.getByRole('button',{name:'Pausa e ajuda',exact:true}).click();
  const pausedTick=await page.locator('span').filter({hasText:/^Tick \d+ ·/}).textContent();
  await page.getByRole('button',{name:'Fechar ajuda mantendo pausa',exact:true}).click();
  assert.equal(await page.locator('span').filter({hasText:/^Tick \d+ ·/}).textContent(),pausedTick);
  page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('button',{name:'Reiniciar',exact:true}).click();
  assert.equal(await page.locator('span').filter({hasText:/^Tick \d+ ·/}).textContent(),pausedTick);
  const originalHash=await page.evaluate(()=>JSON.parse(localStorage.getItem('aurum:itaipu:autosave:v1')).finalHash);
  await page.getByRole('combobox',{name:'Tamanho da interface',exact:true}).selectOption('115');
  await page.reload();await page.getByText('Save local verificado e recuperado. Partida pausada.',{exact:true}).waitFor();
  assert.equal(await page.getByRole('combobox',{name:'Tamanho da interface',exact:true}).inputValue(),'115');
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('aurum:itaipu:autosave:v1')).finalHash),originalHash);
  await page.getByRole('combobox',{name:'Tamanho da interface',exact:true}).selectOption('100');
  outcomes.push({id:'DEV-23/25',flow:'preferences survive reload without changing game hash; tutorial only completes on observed service',status:'PASS'});
  await page.getByText('Linha do tempo',{exact:true}).click();
  await page.getByRole('combobox',{name:'Filtrar eventos',exact:true}).selectOption('construction');
  await page.getByRole('button',{name:'Localizar',exact:true}).first().click();
  await page.locator('p').filter({hasText:/^site:itaipu-ui-1 · operational$/}).waitFor();
  await page.getByRole('combobox',{name:'Filtrar eventos',exact:true}).selectOption('delivered');
  assert(await page.getByRole('button',{name:'Localizar',exact:true}).count()>0);
  await page.getByRole('button',{name:'Aumentar zoom',exact:true}).click();
  await page.getByRole('button',{name:'Diminuir zoom',exact:true}).click();
  await page.getByRole('checkbox',{name:'Terreno e ruas',exact:true}).uncheck();
  await page.getByRole('checkbox',{name:'Terreno e ruas',exact:true}).check();
  const mainBefore=await canvas.screenshot();
  await page.locator('canvas').nth(1).click({position:{x:120,y:75}});
  await page.evaluate(()=>new Promise(requestAnimationFrame));
  assert.notDeepEqual(await canvas.screenshot(),mainBefore);
  outcomes.push({id:'DEV-13/14/15/24',flow:'layers, zoom, pause help',status:'PASS'});
  await page.screenshot({path:'evidence/tasks-desktop.png',fullPage:true});
  const mobile=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
  const touch=await mobile.newPage();touch.on('pageerror',e=>errors.push(String(e)));
  await touch.goto(origin+'/itaipu');await touch.getByText('Estruturas e lotes — alternativa ao mapa',{exact:true}).tap();
  await touch.getByRole('button',{name:'Lote 1',exact:true}).tap();await touch.getByRole('button',{name:'Construir casa',exact:true}).tap();
  await touch.getByRole('button',{name:'Pausar',exact:true}).tap();
  const touchDownload=touch.waitForEvent('download');await touch.getByRole('button',{name:'Verificar e salvar partida',exact:true}).tap();await touchDownload;
  assert(await touch.locator('main').evaluate(el=>el.scrollWidth<=window.innerWidth));
  await touch.screenshot({path:'evidence/tasks-mobile.png',fullPage:true});
  outcomes.push({id:'DEV-20/21/22/67',flow:'390px touch select/build/pause/save, no horizontal main overflow; accessible list',status:'PASS'});
  const feedback=await browser.newContext();const sounds=await feedback.newPage();
  await sounds.addInitScript(()=>{window.__tones=0;const original=AudioContext.prototype.createOscillator;AudioContext.prototype.createOscillator=function(...args){window.__tones++;return original.apply(this,args);};});
  await sounds.goto(origin+'/itaipu');await sounds.getByRole('button',{name:'+1 tick',exact:true}).waitFor();
  await sounds.getByRole('slider',{name:'Volume',exact:true}).click();
  await sounds.getByRole('button',{name:'Construir casa',exact:true}).click();await sounds.getByRole('button',{name:'Pausar',exact:true}).click();
  const tones=await sounds.evaluate(()=>window.__tones);assert(tones>0);
  const working=await sounds.getByRole('button',{name:'Rodar',exact:true}).isVisible();assert(working);
  await sounds.getByRole('button',{name:'Aumentar zoom',exact:true}).click();
  await sounds.getByRole('button',{name:'Diminuir zoom',exact:true}).click();
  assert.equal(await sounds.evaluate(()=>window.__tones),tones);
  await sounds.getByRole('checkbox',{name:'Reduzir movimento e sinais',exact:true}).check();
  outcomes.push({id:'DEV-16',flow:'optional real WebAudio signal follows canonical event; camera renders do not repeat sound',status:'PASS'});
  assert.deepEqual(errors,[]);
  await writeFile(process.env.AURUM_RELEASE_SERVER?'evidence/release-browser-qa.json':'evidence/browser-qa.json',JSON.stringify({browser:await browser.version(),origin,releaseServer:process.env.AURUM_RELEASE_SERVER??null,viewports:[{width:1280,height:1000},{width:390,height:844}],outcomes,errors,limits:'Chromium desktop and touch emulation; no physical phone, Firefox or Safari certification'},null,2)+'\n');
  console.log(JSON.stringify({passed:outcomes.length,errors}));
} finally {if(browser)await browser.close();server.kill('SIGTERM');await mkdir('evidence',{recursive:true});await writeFile('evidence/browser-server.log',log);}
